id: AE3E9B00B
title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
type: translation
pechas:
- ICDACD17D
- I2454083B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:00:34.896687
  last_modified_at: 2023-01-04 12:00:34.896709
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  ICDACD17D/C4CF: 448F
  I2454083B/3021: 448F
